/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as PedirAjudaRouteImport } from './routes/pedir-ajuda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirAjudaRoute = PedirAjudaRouteImport.update({
  id: '/pedir-ajuda',
  path: '/pedir-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doar': typeof DoarRoute
  '/pedir-ajuda': typeof PedirAjudaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doar': typeof DoarRoute
  '/pedir-ajuda': typeof PedirAjudaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doar': typeof DoarRoute
  '/pedir-ajuda': typeof PedirAjudaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doar' | '/pedir-ajuda'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doar' | '/pedir-ajuda'
  id: '__root__' | '/' | '/doar' | '/pedir-ajuda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoarRoute: typeof DoarRoute
  PedirAjudaRoute: typeof PedirAjudaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir-ajuda': {
      id: '/pedir-ajuda'
      path: '/pedir-ajuda'
      fullPath: '/pedir-ajuda'
      preLoaderRoute: typeof PedirAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoarRoute: DoarRoute,
  PedirAjudaRoute: PedirAjudaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
