/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcessibilidadeRouteImport } from './routes/acessibilidade'
import { Route as ApoiarRouteImport } from './routes/apoiar'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AtivarAdminRouteImport } from './routes/ativar-admin'
import { Route as AtivarColaboradorRouteImport } from './routes/ativar-colaborador'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PedirAjudaRouteImport } from './routes/pedir-ajuda'
import { Route as PontosRouteImport } from './routes/pontos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatosRouteImport } from './routes/relatos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as VoluntariosRouteImport } from './routes/voluntarios'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCadastrarPontoRouteImport } from './routes/_authenticated/cadastrar-ponto'
import { Route as AuthenticatedColaboradorRouteImport } from './routes/_authenticated/colaborador'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as PontosPointIdRouteImport } from './routes/pontos.$pointId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminComunidadeRouteImport } from './routes/_authenticated/admin.comunidade'
import { Route as AuthenticatedAdminCuradoriaRouteImport } from './routes/_authenticated/admin.curadoria'
import { Route as AuthenticatedAdminNecessidadesRouteImport } from './routes/_authenticated/admin.necessidades'
import { Route as AuthenticatedAdminSegurancaRouteImport } from './routes/_authenticated/admin.seguranca'
import { Route as AuthenticatedAdminTimeRouteImport } from './routes/_authenticated/admin.time'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminVisaoGeralRouteImport } from './routes/_authenticated/admin.visao-geral'
import { Route as AuthenticatedAdminVoluntariosRouteImport } from './routes/_authenticated/admin.voluntarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessibilidadeRoute = AcessibilidadeRouteImport.update({
  id: '/acessibilidade',
  path: '/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoiarRoute = ApoiarRouteImport.update({
  id: '/apoiar',
  path: '/apoiar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarAdminRoute = AtivarAdminRouteImport.update({
  id: '/ativar-admin',
  path: '/ativar-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarColaboradorRoute = AtivarColaboradorRouteImport.update({
  id: '/ativar-colaborador',
  path: '/ativar-colaborador',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirAjudaRoute = PedirAjudaRouteImport.update({
  id: '/pedir-ajuda',
  path: '/pedir-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const PontosRoute = PontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatosRoute = RelatosRouteImport.update({
  id: '/relatos',
  path: '/relatos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosRoute = VoluntariosRouteImport.update({
  id: '/voluntarios',
  path: '/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrarPontoRoute =
  AuthenticatedCadastrarPontoRouteImport.update({
    id: '/cadastrar-ponto',
    path: '/cadastrar-ponto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradorRoute =
  AuthenticatedColaboradorRouteImport.update({
    id: '/colaborador',
    path: '/colaborador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PontosPointIdRoute = PontosPointIdRouteImport.update({
  id: '/$pointId',
  path: '/$pointId',
  getParentRoute: () => PontosRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComunidadeRoute =
  AuthenticatedAdminComunidadeRouteImport.update({
    id: '/comunidade',
    path: '/comunidade',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuradoriaRoute =
  AuthenticatedAdminCuradoriaRouteImport.update({
    id: '/curadoria',
    path: '/curadoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNecessidadesRoute =
  AuthenticatedAdminNecessidadesRouteImport.update({
    id: '/necessidades',
    path: '/necessidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSegurancaRoute =
  AuthenticatedAdminSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTimeRoute = AuthenticatedAdminTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVisaoGeralRoute =
  AuthenticatedAdminVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVoluntariosRoute =
  AuthenticatedAdminVoluntariosRouteImport.update({
    id: '/voluntarios',
    path: '/voluntarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/apoiar': typeof ApoiarRoute
  '/assistente': typeof AssistenteRoute
  '/ativar-admin': typeof AtivarAdminRoute
  '/ativar-colaborador': typeof AtivarColaboradorRoute
  '/doar': typeof DoarRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/mcp': typeof McpRoute
  '/pedir-ajuda': typeof PedirAjudaRoute
  '/pontos': typeof PontosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatos': typeof RelatosRoute
  '/sobre': typeof SobreRoute
  '/voluntarios': typeof VoluntariosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cadastrar-ponto': typeof AuthenticatedCadastrarPontoRoute
  '/colaborador': typeof AuthenticatedColaboradorRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/pontos/$pointId': typeof PontosPointIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/comunidade': typeof AuthenticatedAdminComunidadeRoute
  '/admin/curadoria': typeof AuthenticatedAdminCuradoriaRoute
  '/admin/necessidades': typeof AuthenticatedAdminNecessidadesRoute
  '/admin/seguranca': typeof AuthenticatedAdminSegurancaRoute
  '/admin/time': typeof AuthenticatedAdminTimeRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/admin/voluntarios': typeof AuthenticatedAdminVoluntariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/apoiar': typeof ApoiarRoute
  '/assistente': typeof AssistenteRoute
  '/ativar-admin': typeof AtivarAdminRoute
  '/ativar-colaborador': typeof AtivarColaboradorRoute
  '/doar': typeof DoarRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/mcp': typeof McpRoute
  '/pedir-ajuda': typeof PedirAjudaRoute
  '/pontos': typeof PontosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatos': typeof RelatosRoute
  '/sobre': typeof SobreRoute
  '/voluntarios': typeof VoluntariosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cadastrar-ponto': typeof AuthenticatedCadastrarPontoRoute
  '/colaborador': typeof AuthenticatedColaboradorRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/pontos/$pointId': typeof PontosPointIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/comunidade': typeof AuthenticatedAdminComunidadeRoute
  '/admin/curadoria': typeof AuthenticatedAdminCuradoriaRoute
  '/admin/necessidades': typeof AuthenticatedAdminNecessidadesRoute
  '/admin/seguranca': typeof AuthenticatedAdminSegurancaRoute
  '/admin/time': typeof AuthenticatedAdminTimeRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/admin/voluntarios': typeof AuthenticatedAdminVoluntariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acessibilidade': typeof AcessibilidadeRoute
  '/apoiar': typeof ApoiarRoute
  '/assistente': typeof AssistenteRoute
  '/ativar-admin': typeof AtivarAdminRoute
  '/ativar-colaborador': typeof AtivarColaboradorRoute
  '/doar': typeof DoarRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/mcp': typeof McpRoute
  '/pedir-ajuda': typeof PedirAjudaRoute
  '/pontos': typeof PontosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatos': typeof RelatosRoute
  '/sobre': typeof SobreRoute
  '/voluntarios': typeof VoluntariosRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cadastrar-ponto': typeof AuthenticatedCadastrarPontoRoute
  '/_authenticated/colaborador': typeof AuthenticatedColaboradorRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/pontos/$pointId': typeof PontosPointIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/comunidade': typeof AuthenticatedAdminComunidadeRoute
  '/_authenticated/admin/curadoria': typeof AuthenticatedAdminCuradoriaRoute
  '/_authenticated/admin/necessidades': typeof AuthenticatedAdminNecessidadesRoute
  '/_authenticated/admin/seguranca': typeof AuthenticatedAdminSegurancaRoute
  '/_authenticated/admin/time': typeof AuthenticatedAdminTimeRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/_authenticated/admin/voluntarios': typeof AuthenticatedAdminVoluntariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessibilidade'
    | '/apoiar'
    | '/assistente'
    | '/ativar-admin'
    | '/ativar-colaborador'
    | '/doar'
    | '/entrar'
    | '/favoritos'
    | '/mcp'
    | '/pedir-ajuda'
    | '/pontos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/relatos'
    | '/sobre'
    | '/voluntarios'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/cadastrar-ponto'
    | '/colaborador'
    | '/minha-conta'
    | '/pontos/$pointId'
    | '/.lovable/oauth/consent'
    | '/admin/categorias'
    | '/admin/comunidade'
    | '/admin/curadoria'
    | '/admin/necessidades'
    | '/admin/seguranca'
    | '/admin/time'
    | '/admin/usuarios'
    | '/admin/visao-geral'
    | '/admin/voluntarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessibilidade'
    | '/apoiar'
    | '/assistente'
    | '/ativar-admin'
    | '/ativar-colaborador'
    | '/doar'
    | '/entrar'
    | '/favoritos'
    | '/mcp'
    | '/pedir-ajuda'
    | '/pontos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/relatos'
    | '/sobre'
    | '/voluntarios'
    | '/.well-known/oauth-protected-resource'
    | '/cadastrar-ponto'
    | '/colaborador'
    | '/minha-conta'
    | '/pontos/$pointId'
    | '/.lovable/oauth/consent'
    | '/admin/categorias'
    | '/admin/comunidade'
    | '/admin/curadoria'
    | '/admin/necessidades'
    | '/admin/seguranca'
    | '/admin/time'
    | '/admin/usuarios'
    | '/admin/visao-geral'
    | '/admin/voluntarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acessibilidade'
    | '/apoiar'
    | '/assistente'
    | '/ativar-admin'
    | '/ativar-colaborador'
    | '/doar'
    | '/entrar'
    | '/favoritos'
    | '/mcp'
    | '/pedir-ajuda'
    | '/pontos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/relatos'
    | '/sobre'
    | '/voluntarios'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/cadastrar-ponto'
    | '/_authenticated/colaborador'
    | '/_authenticated/minha-conta'
    | '/pontos/$pointId'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/comunidade'
    | '/_authenticated/admin/curadoria'
    | '/_authenticated/admin/necessidades'
    | '/_authenticated/admin/seguranca'
    | '/_authenticated/admin/time'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/visao-geral'
    | '/_authenticated/admin/voluntarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessibilidadeRoute: typeof AcessibilidadeRoute
  ApoiarRoute: typeof ApoiarRoute
  AssistenteRoute: typeof AssistenteRoute
  AtivarAdminRoute: typeof AtivarAdminRoute
  AtivarColaboradorRoute: typeof AtivarColaboradorRoute
  DoarRoute: typeof DoarRoute
  EntrarRoute: typeof EntrarRoute
  FavoritosRoute: typeof FavoritosRoute
  McpRoute: typeof McpRoute
  PedirAjudaRoute: typeof PedirAjudaRoute
  PontosRoute: typeof PontosRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatosRoute: typeof RelatosRoute
  SobreRoute: typeof SobreRoute
  VoluntariosRoute: typeof VoluntariosRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessibilidade': {
      id: '/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/acessibilidade'
      preLoaderRoute: typeof AcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoiar': {
      id: '/apoiar'
      path: '/apoiar'
      fullPath: '/apoiar'
      preLoaderRoute: typeof ApoiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar-admin': {
      id: '/ativar-admin'
      path: '/ativar-admin'
      fullPath: '/ativar-admin'
      preLoaderRoute: typeof AtivarAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar-colaborador': {
      id: '/ativar-colaborador'
      path: '/ativar-colaborador'
      fullPath: '/ativar-colaborador'
      preLoaderRoute: typeof AtivarColaboradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir-ajuda': {
      id: '/pedir-ajuda'
      path: '/pedir-ajuda'
      fullPath: '/pedir-ajuda'
      preLoaderRoute: typeof PedirAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontos': {
      id: '/pontos'
      path: '/pontos'
      fullPath: '/pontos'
      preLoaderRoute: typeof PontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatos': {
      id: '/relatos'
      path: '/relatos'
      fullPath: '/relatos'
      preLoaderRoute: typeof RelatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios': {
      id: '/voluntarios'
      path: '/voluntarios'
      fullPath: '/voluntarios'
      preLoaderRoute: typeof VoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastrar-ponto': {
      id: '/_authenticated/cadastrar-ponto'
      path: '/cadastrar-ponto'
      fullPath: '/cadastrar-ponto'
      preLoaderRoute: typeof AuthenticatedCadastrarPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaborador': {
      id: '/_authenticated/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof AuthenticatedColaboradorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pontos/$pointId': {
      id: '/pontos/$pointId'
      path: '/$pointId'
      fullPath: '/pontos/$pointId'
      preLoaderRoute: typeof PontosPointIdRouteImport
      parentRoute: typeof PontosRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comunidade': {
      id: '/_authenticated/admin/comunidade'
      path: '/comunidade'
      fullPath: '/admin/comunidade'
      preLoaderRoute: typeof AuthenticatedAdminComunidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/curadoria': {
      id: '/_authenticated/admin/curadoria'
      path: '/curadoria'
      fullPath: '/admin/curadoria'
      preLoaderRoute: typeof AuthenticatedAdminCuradoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/necessidades': {
      id: '/_authenticated/admin/necessidades'
      path: '/necessidades'
      fullPath: '/admin/necessidades'
      preLoaderRoute: typeof AuthenticatedAdminNecessidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seguranca': {
      id: '/_authenticated/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AuthenticatedAdminSegurancaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/time': {
      id: '/_authenticated/admin/time'
      path: '/time'
      fullPath: '/admin/time'
      preLoaderRoute: typeof AuthenticatedAdminTimeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/visao-geral': {
      id: '/_authenticated/admin/visao-geral'
      path: '/visao-geral'
      fullPath: '/admin/visao-geral'
      preLoaderRoute: typeof AuthenticatedAdminVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/voluntarios': {
      id: '/_authenticated/admin/voluntarios'
      path: '/voluntarios'
      fullPath: '/admin/voluntarios'
      preLoaderRoute: typeof AuthenticatedAdminVoluntariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminComunidadeRoute: typeof AuthenticatedAdminComunidadeRoute
  AuthenticatedAdminCuradoriaRoute: typeof AuthenticatedAdminCuradoriaRoute
  AuthenticatedAdminNecessidadesRoute: typeof AuthenticatedAdminNecessidadesRoute
  AuthenticatedAdminSegurancaRoute: typeof AuthenticatedAdminSegurancaRoute
  AuthenticatedAdminTimeRoute: typeof AuthenticatedAdminTimeRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVisaoGeralRoute: typeof AuthenticatedAdminVisaoGeralRoute
  AuthenticatedAdminVoluntariosRoute: typeof AuthenticatedAdminVoluntariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminComunidadeRoute: AuthenticatedAdminComunidadeRoute,
  AuthenticatedAdminCuradoriaRoute: AuthenticatedAdminCuradoriaRoute,
  AuthenticatedAdminNecessidadesRoute: AuthenticatedAdminNecessidadesRoute,
  AuthenticatedAdminSegurancaRoute: AuthenticatedAdminSegurancaRoute,
  AuthenticatedAdminTimeRoute: AuthenticatedAdminTimeRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVisaoGeralRoute: AuthenticatedAdminVisaoGeralRoute,
  AuthenticatedAdminVoluntariosRoute: AuthenticatedAdminVoluntariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCadastrarPontoRoute: typeof AuthenticatedCadastrarPontoRoute
  AuthenticatedColaboradorRoute: typeof AuthenticatedColaboradorRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCadastrarPontoRoute: AuthenticatedCadastrarPontoRoute,
  AuthenticatedColaboradorRoute: AuthenticatedColaboradorRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PontosRouteChildren {
  PontosPointIdRoute: typeof PontosPointIdRoute
}

const PontosRouteChildren: PontosRouteChildren = {
  PontosPointIdRoute: PontosPointIdRoute,
}

const PontosRouteWithChildren =
  PontosRoute._addFileChildren(PontosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessibilidadeRoute: AcessibilidadeRoute,
  ApoiarRoute: ApoiarRoute,
  AssistenteRoute: AssistenteRoute,
  AtivarAdminRoute: AtivarAdminRoute,
  AtivarColaboradorRoute: AtivarColaboradorRoute,
  DoarRoute: DoarRoute,
  EntrarRoute: EntrarRoute,
  FavoritosRoute: FavoritosRoute,
  McpRoute: McpRoute,
  PedirAjudaRoute: PedirAjudaRoute,
  PontosRoute: PontosRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatosRoute: RelatosRoute,
  SobreRoute: SobreRoute,
  VoluntariosRoute: VoluntariosRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
